version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

networks:
  intra:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/jayi/data/db_data/"
  wordpress_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/jayi/data/wordpress_data/"
