version: '3'

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/data/mariadb:/var/lib/mysql"
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "~/data/website:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "~/data/website:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - intra
    restart: always
    env_file:
      - .env
    tty: true

networks:
  intra:
    driver: bridge
